Add customized dataset for cifar10 and cifar100
lizekai-richard/LDM4DD pull request #1
Opened 2024-03-16 10:14 UTC by ZhaoPeiduo

2024-03-16 10:19 UTC, lizekai-richard requested changes
This one is just an example given by the original repo. I believe we need to do some changes in our case. For example, the condition here should be the label encoding instead of the half image.

2024-03-16 10:22 UTC, ZhaoPeiduo commented
> This one is just an example given by the original repo. I believe we need to do some changes in our case. For example, the condition here should be the label encoding instead of the half image.

Hmm do you have a list of things to change (or at least where I can look for things to customize)?

2024-03-16 11:07 UTC, lizekai-richard commented
> > This one is just an example given by the original repo. I believe we need to do some changes in our case. For example, the condition here should be the label encoding instead of the half image.
> 
> Hmm do you have a list of things to change (or at least where I can look for things to customize)?

The most obvious one should be the condition. Also, the resolution might be different. We can discuss more in detail tomorrow.

2024-03-17 03:06 UTC, ZhaoPeiduo commented on datasets/cifar_custom.py
> +            condition = label
Use one hot encoding to represent the condition

2024-03-17 03:11 UTC, ZhaoPeiduo commented on datasets/cifar_custom.py
> +            image = resize_transform(image)
Delete this part since already handled by train_llm.py

2024-03-17 03:30 UTC, merged